package enums;

public enum ExpressionType {
  NUMBER, WORD, PARAM_NAME, REFERENCE, PAREN_EXPR, COMPARE_EXPR, BOOL_EXPR, BINARY_EXPR,
  UNARY_EXPRESSION, SET_INIT_EXPR, SET_ASSIGN_EXPR, MATRIX_ASSIGN_EXPR,
  PARAMETERIZED_SET_ASSIGN, PARAMETERIZED_MATRIX_ASSIGN, FOR_EXPR, IF_EXPR, VAR_DEFINING_EXPR;
}
