package enums;

public enum ExpressionType {
  REFERENCE, SIMPLE, PAREN_EXPR, COMPARE_EXPR, BOOL_EXPR, BINARY_EXPR,
  ONE_PARAM_UNARY_EXPRESSION, TWO_PARAM_UNARY_EXPRESSION, SET_INIT_EXPR, SET_ASSIGN_EXPR, MATRIX_ASSIGN_EXPR,
  PARAMETERIZED_SET_ASSIGN, PARAMTERIZED_MATRIX_ASSIGN, FOR_EXPR, VAR_DEFINING_EXPR;
}
